[mgr]
ratio = [1, 3, 4]
linemode = "size_and_mtime"

[preview]
image_quality = 80

[opener]
pdf = [{ run = 'tdf "$@"', block = true }]
edit = [{ run = 'nvim "$@"', block = true }]

[open]
prepend_rules = [{ mime = "application/pdf", use = "pdf" }]
